// <auto-generated />
using System;
using HazelNet_Infrastracture.DBContext;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace HazelNet_Infrastractire.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260330110542_Add description property to deck")]
    partial class Adddescriptionpropertytodeck
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("HazelNet_Domain.Models.Card", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("BackOfCard")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreationDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("DeckId")
                        .HasColumnType("integer");

                    b.Property<double>("Difficulty")
                        .HasColumnType("double precision");

                    b.Property<DateTime>("Due")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("ElapsedDays")
                        .HasColumnType("numeric(20,0)");

                    b.Property<string>("FrontOfCard")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<decimal>("Lapses")
                        .HasColumnType("numeric(20,0)");

                    b.Property<DateTime>("LastReview")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("Reps")
                        .HasColumnType("numeric(20,0)");

                    b.Property<decimal>("ScheduledDays")
                        .HasColumnType("numeric(20,0)");

                    b.Property<double>("Stability")
                        .HasColumnType("double precision");

                    b.Property<short>("State")
                        .HasColumnType("smallint");

                    b.HasKey("Id");

                    b.HasIndex("DeckId");

                    b.ToTable("Cards");
                });

            modelBuilder.Entity("HazelNet_Domain.Models.Deck", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreationDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DeckDescription")
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)");

                    b.Property<string>("DeckName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime>("LastAcess")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Decks");
                });

            modelBuilder.Entity("HazelNet_Domain.Models.ReviewHistory", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("integer");

                    b.Property<int>("CardId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("CardId")
                        .IsUnique();

                    b.ToTable("ReviewHistory");
                });

            modelBuilder.Entity("HazelNet_Domain.Models.ReviewLog", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("integer");

                    b.Property<decimal>("ElapsedDays")
                        .HasColumnType("numeric(20,0)");

                    b.Property<short>("Rating")
                        .HasColumnType("smallint");

                    b.Property<DateTime>("Review")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("ReviewHistoryId")
                        .HasColumnType("integer");

                    b.Property<decimal>("ScheduledDays")
                        .HasColumnType("numeric(20,0)");

                    b.Property<short>("State")
                        .HasColumnType("smallint");

                    b.HasKey("Id");

                    b.HasIndex("ReviewHistoryId");

                    b.ToTable("ReviewLogs");
                });

            modelBuilder.Entity("HazelNet_Domain.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("EmailAddress")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.HasKey("Id");

                    b.ToTable("User");
                });

            modelBuilder.Entity("HazelNet_Domain.Models.Card", b =>
                {
                    b.HasOne("HazelNet_Domain.Models.Deck", "Deck")
                        .WithMany("Cards")
                        .HasForeignKey("DeckId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Deck");
                });

            modelBuilder.Entity("HazelNet_Domain.Models.Deck", b =>
                {
                    b.HasOne("HazelNet_Domain.Models.User", "User")
                        .WithMany("Decks")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("HazelNet_Domain.Models.ReviewHistory", b =>
                {
                    b.HasOne("HazelNet_Domain.Models.Card", "Card")
                        .WithOne("ReviewHistory")
                        .HasForeignKey("HazelNet_Domain.Models.ReviewHistory", "CardId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Card");
                });

            modelBuilder.Entity("HazelNet_Domain.Models.ReviewLog", b =>
                {
                    b.HasOne("HazelNet_Domain.Models.ReviewHistory", "ReviewHistory")
                        .WithMany("ReviewLogs")
                        .HasForeignKey("ReviewHistoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ReviewHistory");
                });

            modelBuilder.Entity("HazelNet_Domain.Models.Card", b =>
                {
                    b.Navigation("ReviewHistory")
                        .IsRequired();
                });

            modelBuilder.Entity("HazelNet_Domain.Models.Deck", b =>
                {
                    b.Navigation("Cards");
                });

            modelBuilder.Entity("HazelNet_Domain.Models.ReviewHistory", b =>
                {
                    b.Navigation("ReviewLogs");
                });

            modelBuilder.Entity("HazelNet_Domain.Models.User", b =>
                {
                    b.Navigation("Decks");
                });
#pragma warning restore 612, 618
        }
    }
}
